apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: scylla-operator
  namespace: scylla-operator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook-server
      app.kubernetes.io/instance: webhook-server
